database:
  user: root
  password: babepass
  net: tcp
  addr: 127.0.0.1:3306
  dbname: babe
  allowNativePasswords: true
  params:
    parseTime: "true"

redis:
  net: tcp
  addr: 127.0.0.1:6379
    
server:
  address: 9000
